# Trigger Waybar toggling by hitting the bottom edge of any monitor.
# See https://github.com/AndreasBackx/waycorner for configuration options.

[toggle_waybar]
enter_command = ["pkill", "-SIGUSR1", "waybar"]
exit_command = ["pkill", "-SIGUSR2", "waybar"]
locations = ["bottom"]
margin = 0
size = 25
timeout_ms = 450
