cheats:
  paths:
    - ~/.config/navi/cheats

finder:
  command: fzf
  overrides: >
    --height=100%
    --layout=reverse
    --info=inline
    --border=none
    --cycle
    --color=fg:#bbbbbb,bg:#191919,hl:#819b69,fg+:#bbbbbb,bg+:#3d3839,hl+:#8bae68
    --color=info:#6099c0,prompt:#819b69,pointer:#de6e7c,marker:#de6e7c,spinner:#6099c0
    --color=border:#3d3839,header:#6099c0,gutter:#191919

shell:
  command: fish
